[package]
name          = "kademlia_routing_table"
readme        = "README.md"
license       = "GPL-3.0"
version       = "0.0.1"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
homepage      = "http://maidsafe.net"
repository    = "https://github.com/maidsafe/kademlia_routing_table"
description   = "Kademlia Routing Table implementation"
documentation = "http://maidsafe.net/kademlia_routing_table/latest"

[dependencies]
