[package]
name          = "kademlia_routing_table"
readme        = "README.md"
license       = "GPL-3.0"
version       = "0.0.3"
authors       = ["MaidSafe Developers <dev@maidsafe.net>"]
homepage      = "http://maidsafe.net"
repository    = "https://github.com/maidsafe/kademlia_routing_table"
description   = "Kademlia Routing Table implementation"
documentation = "http://maidsafe.net/kademlia_routing_table/latest"

[dependencies]
log = "~0.3.3"
maidsafe_utilities = "~0.1.3"
itertools = "~0.4.3"
rand = "~0.3.12"
xor_name = "~0.0.1"

[dev-dependencies]
bit-vec = "~0.4.2"
