[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Kademlia Routing Table implementation"
documentation = "http://maidsafe.net/kademlia_routing_table/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "kademlia_routing_table"
readme = "README.md"
repository = "https://github.com/maidsafe/kademlia_routing_table"
version = "0.0.4"

[dependencies]
itertools = "~0.4.3"
log = "~0.3.3"
maidsafe_utilities = "~0.1.3"
rand = "~0.3.12"
xor_name = "~0.0.1"

[dev-dependencies]
bit-vec = "~0.4.2"
